# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "batch-job-rules.yml"
  - "dead-mans-snitch-rule.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]


  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]


  - job_name: "alertmanager"
    honor_labels: true
    static_configs:
      - targets: ["alertmanager:9093"]


  - job_name: "SERVER-999"
    static_configs:
      - targets: ["192.168.1.209:9100"]

  - job_name: "SERVER-888"
    static_configs:
      - targets: ["192.168.1.208:9100"]

      
  - job_name: "mysqld-exporter"
    static_configs:
      - targets: ["mysqld-exporter:9104"]

