version: "3"

networks:
  watchdog_watchdog:
    external: true


services:
  mysqld:
    image: mysql:8.0.33-debian
    container_name: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: 'ahmed@1998'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASS: 'mysql_pass'
    volumes:
      - "$PWD/mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - watchdog_watchdog


  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    command: |
      --mysqld.address="mysqld:3306"
      --config.my-cnf="/tmp/.my.cnf"
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:exporter@(mysqld:3306)/
    volumes:
      - "$PWD/mysql-exporter/my.cnf:/tmp/.my.cnf"
    ports:
      - 9104:9104
    networks:
      - watchdog_watchdog
    depends_on:
      - mysqld

      
